name: ani-snake

on:
  schedule:
    - cron: "0 */12 * * *" 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Generate Snake Animation
      - name: Generate Snake Animation
        uses: ./
        with:
          github_user_name: ${{ github.repository_owner }}  
          outputs: |
            dist/ocean.gif?color_snake=blue&color_dots=#161b22,#0e4429,#006d32,#26a641,#39d353

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output  
          build_dir: dist 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

  
