name: ani-snake

on:
  schedule:
    - cron: "0 */12 * * *" 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Generate Snake Animation (GIF - LIGHT)
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: lachimo 
          outputs: |
            dist/ocean-light.gif?color_snake=#e1c4e0&color_dots=#ffe6ec,#ffc2d1,#feb3c7,#ff8fab,#fb6f92

            

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output  
          build_dir: dist 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

  
